# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-22 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0005_auto_20160606_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='page',
            new_name='contributor',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
    ]
