# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0008_auto_20160823_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='user_login_time',
            field=models.CharField(default=0, max_length=100, verbose_name='最終ログイン時間'),
            preserve_default=False,
        ),
    ]
