# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0009_report_user_login_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='impression',
            name='coment_time',
            field=models.CharField(default=0, max_length=255, verbose_name='コメント時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='impression',
            name='comment_user',
            field=models.CharField(default=0, max_length=255, verbose_name='コメント投稿者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='impression',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='day.Report', verbose_name='日報'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user_login_time',
            field=models.CharField(max_length=255, verbose_name='最終ログイン時間'),
        ),
    ]
