# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0010_auto_20160824_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impression',
            old_name='coment_time',
            new_name='comment_time',
        ),
    ]
