# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0011_auto_20160824_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user_login_time',
        ),
        migrations.AddField(
            model_name='report',
            name='user_post_time',
            field=models.CharField(default=0, max_length=255, verbose_name='投稿時間'),
            preserve_default=False,
        ),
    ]
