# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0012_auto_20160824_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_keyword', models.CharField(max_length=255, verbose_name='検索ワード')),
            ],
        ),
    ]
