# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-25 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0013_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
