# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-14 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0014_delete_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='user_post_time',
            new_name='post_time',
        ),
    ]
