# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-14 07:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0016_auto_20160914_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 14, 7, 26, 38, 314317, tzinfo=utc), verbose_name='作成時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='post_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 14, 7, 26, 45, 101995, tzinfo=utc), verbose_name='投稿時間'),
            preserve_default=False,
        ),
    ]
