# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-17 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0019_auto_20160930_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_content', models.TextField(blank=True, verbose_name='質問内容')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='day.Report', verbose_name='日報')),
            ],
        ),
        migrations.RemoveField(
            model_name='questionlevel',
            name='report',
        ),
        migrations.DeleteModel(
            name='QuestionLevel',
        ),
    ]
