# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0002_auto_20160602_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page',
            field=models.IntegerField(blank=True, default=0, verbose_name='ページ数'),
        ),
    ]
