# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0004_auto_20160603_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page',
            field=models.CharField(max_length=255, verbose_name='投稿者'),
        ),
    ]
